= Lab Guide: Create a GnuPG Keypair


_A guide to creating a GPG keypair that will be used to sign a local project using `ansible-sign`._

---

[discrete]
====
*Estimated time to complete: 5 minutes*
====

In this challenge, we will create a GnuPG keypair to sign projects locally. Asynchronous keys are used to validate the integrity of a project's content. The private key from the keypair is used at the point of signing, and the public key is used to verify that the content has not been manipulated. This public key will be used in automation controller to verify signatures.

---

== Task 1: Open the gpg.txt file and check its contents

First, run the following command in the terminal window to check the contents of the `gpg.txt` file:

[source,bash]
----
cat ~/gpg.txt
----

Think of this file as the instructions given to the GnuPG library on the system about the type of keypair we want to create. This creates a keypair without a passphrase. If you want to know more about GPG key generation, please follow this link:https://www.redhat.com/sysadmin/creating-gpg-keypairs[link].

---

== Task 2: Create GPG keypair using the gpg.txt file

Run the following commands in the Terminal window to create the keypair. The first command will create the keypair using the `gpg.txt` file:

[source,bash]
----
gpg --batch --gen-key ~/gpg.txt
----

The next command will export the public key between plaintext headers and footers (ASCII armor) into a file called `signing_demo.asc`. This is a conventional method for sharing public keys.

[source,bash]
----
gpg --output ~/signing_demo.asc --armor --export
----

Check the content of the exported public key using the below command:

[source,bash]
----
cat ~/signing_demo.asc
----

We will use all the contents of this file in the next challenges when we show the verification of projects in automation controller.

---

== Task 3: Verify if the created keypair shows on the system

Run the below command to list the GPG keys that exist on the system. This list should now include the keypair you just created.

[source,bash]
----
gpg --list-keys
----

---

== Summary

* We created a GPG keypair in the default system keystore; the private key will be used to sign an Ansible project locally.
* We exported the public key to a file and will use the contents of that file in automation controller in the next challenges to verify the project.

== Next Challenge

Press the `Next` button below to go to the next challenge once you've completed the tasks.

== Encountered an issue?

If you have encountered an issue or have noticed something not quite right, please link:https://github.com/ansible/workshops/issues/new[open an issue].
